version: '3'
services:
  frontend: 
    container_name: frontend
    image: yoloshikudkr/3t-front
    ports: 
      - "80:80"
    depends_on:
      - backend
    networks:
      - three-tier-net 
  backend:
    container_name: backend
    image: yoloshikudkr/3t-back
    ports: 
      - "3500:3500"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql123
      - MYSQL_DATABASE=school
    depends_on:
      - db
    networks:
      - three-tier-net
  db:
    container_name: mysql-container
    image: yoloshikudkr/3t-db
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123
      - MYSQL_DATABASE=school
    networks:
      - three-tier-net
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
networks:
  three-tier-net:
    name: three-tier-net
    driver: bridge
