apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yoloshikudkr/3t-front:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://140.83.85.226:32000"
