apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_DATABASE: c2Nob29s  # base64 encoded value of 'school'
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw== # base64 encoded value of 'root123'

